{% set name = "pymagicc" %}
{% set version = "2.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 689359bf39f40cf3e7f6ed7ef411b0b26e40e79308839a5ee15cb2575e760434

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - pip
    - python >=3.9
    - versioneer

  host:
    - pip
    - python >=3.9
    - versioneer

  run:
    - python >=3.9
    - pandas-datapackage-reader
    - f90nml
    - PyYAML
    - scmdata
    - pandas

test:
  imports:
    - pymagicc

  commands:
    - python -c "import pymagicc; assert pymagicc.__version__ == '{{ version }}'"

about:
  home: https://github.com/openclimatedata/pymagicc
  license: BSD-3-Clause AND CC-BY-NC-SA-3.0
  license_family: BSD
  license_file:
    - LICENSE
    - pymagicc/MAGICC6/License_MAGICC6Executable.txt
  summary: Python wrapper for the simple climate model MAGICC
  doc_url: https://pymagicc.readthedocs.io/en/latest/
  dev_url: https://github.com/openscm/pymagicc

extra:
  recipe-maintainers:
    - znicholls
    - rgieseke
